#!/bin/sh
#
# Shell script wrapper to convert Lua to C and optionally
# compile and run it.
#
# option -c causes compilation only (no run)
# option -C causes C source generation only (no compile or run)

pushd "`dirname \"$0\"`" > /dev/null
export CWD="$PWD"
popd > /dev/null

# You may need to change these variables:
LUA=lua
CC=clang
XCODE_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/"
CFLAGS="-O3 -fomit-frame-pointer -DNDEBUG -Wall -Isrc -I${XCODE_PATH} -Wno-nullability-completeness"
#CFLAGS="-O2 -DNDEBUG -Wall -Ilua/src"
#CFLAGS=-g
LFLAGS="-Lsrc -llua5.1"
LUA2C="${LUA} lua2cc.lua"
#LUA2C="./lua2c"

COMPILEONLY=
if [ "$1" = "--compile" ]
then
  COMPILEONLY=1
  shift
elif [ "$1" = "--source" ]
then
  COMPILEONLY=2
  shift
fi
if [ "$1" = "" ]
then
  echo "usage: clua [options] [filename.lua] ..."
  echo "  options:"
  echo "  nothing mean to make source + compile + run"
  echo "    --compile  compile only (no run)"
  echo "    --source   generate C source only (no compile or run)"
  exit 1
fi

LUAFILE=$1
FILENAME=${LUAFILE%.*}

if [ "$2" = "" ] 
then 
  CFILE="${FILENAME}.c"
  OUTPUT="${FILENAME}"
else 
  CFILE="$2.c"
  OUTPUT="$2"
  shift
fi 

if [ "$COMPILEONLY" = "2" ]
then
  LUA_PATH=$CWD/?.lua ${LUA2C} ${LUAFILE} > ${CFILE} || exit 1
  exit 0
fi


if [ "$COMPILEONLY" = "1" ]
then
  ${CC} ${CFLAGS} ${CFILE} -o ${OUTPUT} ${LFLAGS} || exit 1
  exit 0
fi

LUA_PATH=$CWD/?.lua ${LUA2C} ${LUAFILE} > ${CFILE} || exit 1
${CC} ${CFLAGS} ${CFILE} -o ${OUTPUT} ${LFLAGS} || exit 1

shift
./${OUTPUT} $@
